FROM ubuntu
RUN apt-get -y update && apt-get -y upgrade \
    && apt-get -y install openjdk-8-jdk
ADD https://downloads.apache.org/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.tar.gz /opt
RUN cd /opt  && tar -zxvf apache-tomcat-8.5.69.tar.gz
ADD https://get.jenkins.io/war-stable/2.289.2/jenkins.war  /opt/apache-tomcat-8.5.69/webapps/jenkins.war
EXPOSE 8080
ENTRYPOINT ["/opt/apache-tomcat-8.5.69/bin/catalina.sh", "run"]
